### ISSUE TITLE
Remote Code Exectuion via unescaped parameter in generateString function

### ISSUE THREAD

**Issue by d90pwn** [yiisoft/yii2-gii#433]
I found an issue that causes Remote Code Execution by improper input validation in a `$this->messageCategory` variable.

As a result, a remote attacker with an access to https://localhost/gii/ endpoint can execute arbitrary PHP code to template file, and then run it.

To fix issue, we can replace the `$str = "Yii::t('" . $this->messageCategory . "', '" . $string . "'" . $ph . ")";` 
to `$str = "Yii::t('" . addslashes($this->messageCategory) . "', '" . $string . "'" . $ph . ")";`
in a file:
https://github.com/yiisoft/yii2-gii/blob/ee4d072af2788208edaed2b24b5acbc34b8631a1/src/Generator.php#L505

**Comment by schmunk42** [comment]
Or a better validation here: https://github.com/yiisoft/yii2-gii/blob/6c63058e3e3d944767e9dfac0e0d2ef4623a6cca/src/generators/model/Generator.php#L95

**Comment by samdark** [comment]
First of all, thanks for reporting it.

1. I don't consider it a huge security issue since Gii should not be enabled on production ever. That's an easy way to disrupt the project by rewriting custom code with generated one.
2. It's good to have it fixed nevertheless.
3. @schmunk42 solution fits it better, I think.
