### ISSUE TITLE
Model generator, add inverseOf to relations.

### ISSUE THREAD

**Issue by nineinchnick** [yiisoft/yii2-gii#54]
I've just implemented this in my model generator. Filling those manually is very error prone (singular vs plural relation names, etc). This be included in core but I've noticed that not all relations need those (excluding many-many). I'd rather remove those unecessary than try to add the required ones.

Should there be an option to generate them, like _generateRelations_? Maybe _generateRelations_ should be a dropdown with options like:

* no relations
* generate relations
* generate relations with inverse

**Comment by samdark** [comment]
Yes, probably.

**Comment by Faryshta** [comment]
thats very tricky, after generating the model usually i go directly to rename the relations because (a) my tables are in spanish, so plural is wrong 90% of the times (b) sometimes my tables have prefixes example `store`, `store_products`, `store_employee` which will generate ugly looking relations that i have to fix as soon as the model is generated.

**Comment by Faryshta** [comment]
i think this is the line where the `inverseOf` should be added https://github.com/yiisoft/yii2-gii/blob/master/generators/model/Generator.php#L427 the things to figure out are:

1) name of the inverse relation

2) if the keys used by the foreign key defined on the referenced table are unique on the original table.
